name: Tapmad Manual Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      - name: Checkout Private Repo Script
        uses: actions/checkout@v3
        with:
          repository: srhady/axsportspvt
          token: ${{ secrets.MY_PAT }}
          path: private_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pycryptodome

      - name: Load Old M3U for Caching from Gist
        run: |
          curl -fL -o tapmad_bd.m3u "https://gist.githubusercontent.com/srhady/fc7a6cd99138fa74090822c84cbe8b73/raw/tapmad_bd.m3u" || echo "Old M3U cache not found"

      - name: Run Script
        run: |
          python private_repo/tapmad_action.py

      - name: Update Secret Gist
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }} 
        run: |
          jq -n \
            --rawfile m3u tapmad_bd.m3u \
            --rawfile json tapmad_bd.json \
            '{"files": {"tapmad_bd.m3u": {"content": $m3u}, "tapmad_bd.json": {"content": $json}}}' > payload.json
          
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /gists/fc7a6cd99138fa74090822c84cbe8b73 \
            --input payload.json
