name: Tapmad Public Update

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          path: public_repo

      - name: Checkout Private Repo Script
        uses: actions/checkout@v3
        with:
          repository: srhady/axsportspvt
          token: ${{ secrets.MY_PAT }}
          path: private_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pycryptodome

      - name: Run Script
        run: |
          cp public_repo/tapmad_data.json . || echo "Old cache not found"
          python private_repo/tapmad_action.py

      - name: Commit and Push to Public
        run: |
          cd public_repo
          git config --local user.name "GitHub Action Bot"
          git config --local user.email "actions@github.com"
          
          mv ../tapmad_bd.m3u . || echo "m3u not found"
          mv ../tapmad_data.json . || echo "json not found"
          
          git add tapmad_bd.m3u tapmad_data.json
          git commit -m "Auto Update: $(date +'%d-%m-%Y %I:%M %p') (BD Time)" || echo "No changes to commit"
          git push
